### ISSUE TITLE
Error after update version 1.2.2

### ISSUE THREAD

**Issue by urtaevS** [joaomgcd/node-red-contrib-join-joaoapps#15]
Just update the node and get error.
ERR_REQUIRE_ESM

**Comment by stephennutt** [comment]
I did update today and got similar issue.

![Join Node Red Error](https://user-images.githubusercontent.com/25011547/182026475-b853d61f-1f6d-4d82-87dc-5c32082b38e3.JPG)

**Comment by falcon1201** [comment]
same error

**Comment by joaomgcd** [comment]
Ok, I've pushed out an update! Sorry for the delay!

https://www.npmjs.com/package/node-red-contrib-join-joaoapps

The node-red palette manager should see it in a few hours. Hope this helps!

**Comment by stephennutt** [comment]
Node Red is still showing Ver 1.2.2 last updated 3 months ago in my Palette Manager.  Is there something I need to do to make it available?  Are others seeing the latest version?

**Comment by joaomgcd** [comment]
Yeah, I already uploaded the new version 2 days ago, not sure why the Node-RED version doesn't get updated :/

**Comment by stephennutt** [comment]
Very strange.  It's still showing only the old version available thru my Palette Manager.

![image](https://user-images.githubusercontent.com/25011547/184536468-c6d4fb0a-134d-4520-84b3-5f46e556c1c5.png)

**Comment by joaomgcd** [comment]
Thanks! But yeah, you're right! For some reason [this page](https://flows.nodered.org/node/node-red-contrib-join-joaoapps) and the palette manager are not getting updated but [this](https://www.npmjs.com/package/node-red-contrib-join-joaoapps) already shows the updated version... You wouldn't know why, would you? 😅

**Comment by strelniece** [comment]
Yes, I know this is closed. But updated from the palette yesterday, with the same error.

Running node-red addon in homeassistant, so no npm.

So I guess I just have to wait untill it has updated to the correct version.

**Comment by sumoneelse** [comment]
Something is amiss here. Still getting this error.  Installing via "npm install node-red-contrib-join-joaoapps" did not correct the issue
